/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworld_MainActivity */

#ifndef _Included_com_example_helloworld_MainActivity
#define _Included_com_example_helloworld_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_helloworld_MainActivity_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
